# -*- coding: utf-8 -*-
"""customer segmentation. Age and Polarity. k-Means clustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgVphL6Qyks5g18dORGcg58wuAR3zfBU
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
path='/content/drive/My Drive/dataset/Clothing Reviews.csv'
df=pd.read_csv(path)

df.head()

df.columns

df.drop(["Unnamed: 0","Clothing ID", "Title"], axis=1, inplace=True)
df.head()

df.isnull().sum()

len(df)

df.describe()

df.dtypes

df['Age'].unique()

df['Class Name'].unique()

df['Recommended IND'].unique()

df['Division Name'].unique()

df['Division Name'].unique()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

"""**Grouping according to Age**"""

df['Age'].value_counts()

df['Age']=df['Age'].astype(int)

"""**dividing age group into categories**"""

def age_cat(age):
    if age < 20:
        return 'teens'
    elif age < 30 :
        return '20s'
    elif age < 40 :
        return '30s'
    elif  age < 50 :
        return '40s'
    elif  age < 60 :
        return '50s'
    elif  age < 70 :
        return '60s'
    else:
        return 'above 70s'

df['age_categorize'] = df['Age'].apply(age_cat)

df.head(3)

df['age_categorize'].value_counts()

plt.figure(figsize=(12,6))
sns.countplot(x='age_categorize',data=df, palette= 'pastel' )
plt.title('Customers in different age groups', fontsize=16)
plt.show()

"""# Sentiment Analysis"""

import string
string.punctuation

df.dtypes

df['Review Text'].head()

df['Review Text'].dtypes

"""Removing the rows that has null values"""

df = df[~df['Review Text'].isnull()]

df['length']=df['Review Text'].apply(len)

df.head()

"""Length after removing the rows where Review Text is null"""

len(df)

plt.figure(figsize=(10,8))
sns.boxplot(x='Recommended IND',y='length',data=df,hue='Rating',palette='rainbow')
plt.title('message length')

df.length.describe()

"""maximum length is 508."""

df[df['length'] == 508]['Review Text'].iloc[0]

"""**Removing puntuations**"""

import string
string.punctuation
def remove_punctuation(text):
    no_punct=[words for words in text if words not in string.punctuation]
    words_wo_punct=''.join(no_punct)
    return words_wo_punct
df['Review Text']=df['Review Text'].apply(lambda x: remove_punctuation(x))
df.head()

"""**Text blob for polarity**"""

from textblob import TextBlob
df.head()

df["Polarity"] = df["Review Text"].apply(lambda x: TextBlob(x).sentiment.polarity)

df.head()

df['Polarity'].min()

def getAnalysis(polarity):
  if polarity < 0:
    return 'Negative'
  elif polarity == 0:
    return 'Neutral'
  else:
    return 'Positive'

df['TextBlob_Analysis']=df['Polarity'].apply(getAnalysis)

df.head(3)

polarity_plot=df['TextBlob_Analysis'].value_counts()

polarity_plot

positive= 21213/len(df)*100
negative= 1333/len(df)*100
neutral= 95/len(df)*100

labels = ['Positive', 'Negative', 'Neutral']
sizes = [positive, negative, neutral]
plt.figure(figsize=(12,7))
plt.pie(sizes, labels=labels,autopct='%1.1f%%',shadow=True, startangle=140)
plt.show()

"""***Label Encoding***"""

#Import label encoder
from sklearn import preprocessing

# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
df['Encoded_value']= label_encoder.fit_transform(df['TextBlob_Analysis'])

df['Encoded_value'].unique()

df.head()

sns.boxplot(x="Rating", y="length", data=df,)

sns.boxplot(x="Encoded_value", y="length", data=df,)

df['Polarity'].min()

df['Polarity'].max()

"""# **K-means clustering**"""

x= df.iloc[:, [0,10]].values

"""**Finding the k value**"""

from sklearn.cluster import KMeans
wcss=[]
for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 42)
    kmeans.fit(x)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

"""Number of clusters is 4. After 4 the value decreases gradually"""

kmeans = KMeans(n_clusters = 4, init = 'k-means++', random_state = 42)
y_pred = kmeans.fit_predict(x)

plt.figure(figsize=(20,10))
plt.scatter(x[y_pred == 0,0],x[y_pred == 0,1],label = 'Cluster-1', s = 60)
plt.scatter(x[y_pred == 1,0],x[y_pred == 1,1],label = 'Cluster-2', s = 60)
plt.scatter(x[y_pred == 2,0],x[y_pred == 2,1],label = 'Cluster-3', s = 60)
plt.scatter(x[y_pred == 3,0],x[y_pred == 3,1],label = 'Cluster-4', s = 60)
plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:, 1], s = 50, c = 'black' , label = 'centeroid',alpha=0.5,edgecolor='darkgrey')
plt.legend()
plt.xlabel('Age of customers')
plt.ylabel('Polarity')
plt.show()

"""The customers are divided into 4 cluster with the average polarity of 0.25. In this dataset, most of the reviews are positive. So we get the points above 0.0."""